version: "3"
services:
  backend:
    image: get-a-ghost-app
    build:
      context: backend
      dockerfile: Dockerfile
    # environment:
    #   - MONGODB_URI=mongodb+srv://moritz:cl5rdrcJtGzeKg0a@cluster0.dg6v9.mongodb.net/get-a-ghost?retryWrites=true&w=majority
    ports:
      - 3000:3000
      - 35729:35729
    volumes:
      - ./backend/src:/app/src
  mongo:
    image: mongo
    ports:
      - 27017:27017
