version: "3"
services:
  #   web:
  #     image: web
  #     build:
  #       context: ./web
  #       dockerfile: Dockerfile.dev
  #     depends_on:
  #       - api
  #     ports:
  #       - 3000:3000
  #     environment:
  #       - HOST=0.0.0.0
  #       - PORT=3000
  #       - BASE_API_URL=http://api:5000/api
  #       - BROWSER_BASE_API_URL=http://localhost:5000/api
  #       # - API_HOST=api
  #       # - API_PORT=5000
  #       # - API_PREFIX=/api
  #     volumes:
  #       - ./web/assets:/app/assets
  #       - ./web/components:/app/components
  #       - ./web/layouts:/app/layouts
  #       - ./web/middleware:/app/middleware
  #       - ./web/server-middleware:/app/server-middleware
  #       - ./web/pages:/app/pages
  #       - ./web/plugins:/app/plugins
  #       - ./web/static:/app/static
  #       - ./web/store:/app/store
  #       - ./web/test:/app/test
  #       - ./web/nuxt.config.js:/app/nuxt.config.js
  api:
    image: api
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    ports:
      - 5000:5000
    volumes:
      - ./api/src:/app/src
      - ./api/.env:/app/.env
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
