version: "3"
services:
  web:
    image: web
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    depends_on:
      - api
    ports:
      - 3000:3000
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - BASE_API_URL=http://api:5000
      - BROWSER_BASE_API_URL=http://localhost:5000
    volumes:
      - ./web:/app
  api:
    image: api
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    ports:
      - 5000:5000
      - 9229:9229
    volumes:
      - ./api/src:/app/src
      - ./api/.env:/app/.env
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    # volumes:
    #   - ./data:/data/db
