FROM node:14-alpine

RUN apk add --no-cache --virtual .gyp \
        python3 \
        make \
        g++

WORKDIR /app

ADD package*.json ./

RUN npm install && apk del .gyp

CMD [ "npm", "run", "dev" ]